apiVersion: apps/v1
kind: Deployment 
metadata: #Dictionary ImagePullBackOff pod
  name: ipbf
spec: # Dictionary
  replicas: 1
  selector:
    matchLabels:
      app: ipbfpod
  template:  
    metadata: # Dictionary
      name: ipbfpod
      labels: # Dictionary
        app: ipbfpod  # Key value paids
    spec:
      containers: # List
        - name: ipbfpodcontainer
          image: stratus1/unavailableimage:na
      nodeSelector:
        kubernetes.io/os: linux
    
